import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import logging
from typing import Dict
from app.config import settings
import os
import tempfile
import subprocess
import shutil

logger = logging.getLogger(__name__)

def generate_latex_report(profiles: Dict, duration: float, total_persons: int, total_violations: int, compliance_score: float, compliance_status: str, violation_counts: dict) -> str:
    duration_mins = int(duration // 60)
    duration_secs = int(duration % 60)
    duration_str = f"{duration_mins}m {duration_secs}s" if duration_mins > 0 else f"{duration_secs}s"

    parts = []
    parts.append(r"""\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{geometry}
\geometry{a4paper, margin=1in}
\usepackage{booktabs}
\usepackage{xcolor}
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}

\begin{document}

\begin{titlepage}
    \centering
    \vspace*{4cm}
    {\huge \textbf{VioTrack Safety Compliance Report} \par}
    \vspace{2cm}
    {\Large \textbf{Automated Computer Vision Audit} \par}
    \vspace{2.5cm}
    {\large \textbf{Date Generated:} \today \par}
    \vspace{0.5cm}
    {\large \textbf{Classification:} Confidential \par}
    \vfill
    {\normalsize This document is entirely auto-generated by the VioTrack analytics engine. \par}
\end{titlepage}

\newpage

\section*{1. Executive Summary}
This automated document serves as the official safety compliance and monitoring report derived from the VioTrack AI pipeline. The system actively processes continuous video feeds to ensure that optimal safety protocols and personal protective equipment (PPE) regulations are strictly adhered to by all personnel present in the monitored zone. 

The deployment of automated computer vision tracking mitigates operational and occupational risks by enabling instantaneous identification of safety violations. This allows management to pursue rapid remediation, targeted training interventions, and comprehensive personnel accountability.

\vspace{0.5cm}

\section*{2. Technical Methodology}
The safety insights provided in this audit are autonomously assembled by an advanced deep learning architecture:
\begin{itemize}
    \item \textbf{Spatial Object Detection (YOLO)}: Real-time localization of individuals and discrete personal protective equipment classes (such as hard hats, safety vests, boots, masks, and goggles) across every frame.
    \item \textbf{Persistent Multi-Object Tracking (DeepSORT)}: Complex kinematic persistence algorithms temporarily assign a unique, re-identifiable "Track ID" to individuals within the camera's field of view, preventing duplicated violation counts for prolonged infractions by a single person.
    \item \textbf{Heuristic Aggregation}: Bounding box proximity mapping is utilized to explicitly attribute detected PPE (or the distinct lack thereof) to the corresponding tracked human subject.
\end{itemize}

\vspace{0.5cm}

\section*{3. Compliance Policies}
Violations are classified into core infractions based on strict industrial safety requirements:
\begin{itemize}
    \item \textbf{No Helmet}: Absence of a rigid hard hat or prescribed protective headgear.
    \item \textbf{No Safety Vest}: Absence of a high-visibility, reflective outer garment covering the torso.
    \item \textbf{No Safety Boots}: Detection of non-compliant footwear on the lower extremities.
    \item \textbf{No Goggles/Face Mask}: Missing designated facial and ocular protection elements.
    \item \textbf{No Gloves}: Unprotected hands in hazard-designated zones.
\end{itemize}

\newpage

\section*{4. Session Summary Data}
\begin{itemize}""")
    
    parts.append(f"    \\item \\textbf{{Total Duration Evaluated:}} {duration_str}")
    parts.append(f"    \\item \\textbf{{Aggregate Persons Tracked:}} {total_persons}")
    parts.append(f"    \\item \\textbf{{Total Safety Violations:}} {total_violations}")
    parts.append(f"    \\item \\textbf{{System Compliance Rating:}} {compliance_score:.0f}\\% ({compliance_status})")
    
    parts.append(r"\end{itemize}")

    if total_violations > 0:
        parts.append(r"""
\section*{Violation Breakdown}
\begin{table}[h]
\centering
\begin{tabular}{lc}
\toprule
\textbf{Violation Type} & \textbf{Incidents} \\
\midrule""")
        for v_type, count in sorted(violation_counts.items(), key=lambda x: x[1], reverse=True):
            parts.append(f"{v_type} & {count} \\\\")
            
        parts.append(r"""\bottomrule
\end{tabular}
\end{table}

\section*{Person Log (Violators Only)}
\begin{table}[h]
\centering
\begin{tabular}{llp{8cm}}
\toprule
\textbf{Track ID} & \textbf{Violations} & \textbf{Details} \\
\midrule""")
        for tid, profile in profiles.items():
            if profile.violation_count > 0:
                details = ", ".join([f"{k} ({v})" for k, v in profile.violation_types.items()])
                parts.append(f"Person-{tid} & {profile.violation_count} & {details} \\\\")
                
        parts.append(r"""\bottomrule
\end{tabular}
\end{table}""")
    else:
        parts.append(r"""
\vspace{1cm}
\begin{center}
\textit{No safety violations were detected during this session. Great job!}
\end{center}""")

    parts.append(r"\end{document}")
    
    return "\n".join(parts)

def send_batch_report_email(profiles: Dict, recipient: str, duration: float = 0.0):
    """
    Generate and send an HTML summary report of safety violations detected during the live stream.
    Also generates a LaTeX report and attaches it as a PDF or .tex file.
    If SMTP server is not configured, it will print a mock email to the logger.
    """
    if not recipient:
        logger.warning("No recipient email provided for batch report. Skipping.")
        return

    # Compile Summary Data
    total_persons = len(profiles)
    total_violations = 0
    violation_counts = {}

    for tid, profile in profiles.items():
        total_violations += profile.violation_count
        for v_type, count in profile.violation_types.items():
            if v_type not in violation_counts:
                violation_counts[v_type] = 0
            violation_counts[v_type] += count

    # Calculate compliance score
    if total_persons > 0:
        violation_rate = total_violations / total_persons
        # Score: 100% = no violations, decreases with each violation per person
        compliance_score = max(0, 100 - (violation_rate * 25))
    else:
        compliance_score = 100.0

    compliance_status = "PASS" if compliance_score >= 70 else "FAIL"
    status_color = "#16a34a" if compliance_status == "PASS" else "#dc2626"
    status_bg = "#dcfce7" if compliance_status == "PASS" else "#fef2f2"

    # Format duration nicely
    duration_mins = int(duration // 60)
    duration_secs = int(duration % 60)
    duration_str = f"{duration_mins}m {duration_secs}s" if duration_mins > 0 else f"{duration_secs}s"

    # Generate HTML Content (to serve as the email body)
    html_parts = []
    html_parts.append(f"""
    <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; color: #333; }}
                h1 {{ color: #2563eb; }}
                h2 {{ color: #1e40af; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }}
                .compliance-banner {{ padding: 20px; border-radius: 10px; margin-bottom: 20px; text-align: center; border: 2px solid {status_color}; background: {status_bg}; }}
                .compliance-score {{ font-size: 48px; font-weight: bold; color: {status_color}; margin: 0; }}
                .compliance-label {{ font-size: 14px; color: #6b7280; text-transform: uppercase; letter-spacing: 1px; }}
                .compliance-status {{ display: inline-block; padding: 6px 20px; border-radius: 20px; font-weight: bold; font-size: 18px; color: white; background: {status_color}; margin-top: 8px; }}
                .summary-box {{ background-color: #f3f4f6; padding: 15px; border-radius: 8px; margin-bottom: 20px; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
                th, td {{ padding: 10px; border-bottom: 1px solid #ddd; text-align: left; }}
                th {{ background-color: #e5e7eb; }}
                .danger {{ color: #dc2626; font-weight: bold; }}
            </style>
        </head>
        <body>
            <h1>VioTrack: Safety Compliance Report</h1>

            <div class="compliance-banner">
                <p class="compliance-label">Overall Compliance Score</p>
                <p class="compliance-score">{compliance_score:.0f}%</p>
                <div class="compliance-status">{compliance_status}</div>
            </div>

            <h2>Session Summary</h2>
            <div class="summary-box">
                <p><strong>Session Duration:</strong> {duration_str}</p>
                <p><strong>Total Persons Tracked:</strong> {total_persons}</p>
                <p><strong>Total Violations Detected:</strong> <span class="{'danger' if total_violations > 0 else ''}">{total_violations}</span></p>
                <p><strong>Compliance Score:</strong> <span style="color: {status_color}; font-weight: bold;">{compliance_score:.0f}% — {compliance_status}</span></p>
            </div>
            
            <p><strong>Note: A detailed LaTeX report is attached to this email.</strong></p>
    """)

    if total_violations > 0:
        html_parts.append("""
            <h2>Violation Breakdown</h2>
            <table>
                <tr>
                    <th>Violation Type</th>
                    <th>Incidents</th>
                </tr>
        """)
        for v_type, count in sorted(violation_counts.items(), key=lambda x: x[1], reverse=True):
            html_parts.append(f"""
                <tr>
                    <td>{v_type}</td>
                    <td>{count}</td>
                </tr>
            """)
        html_parts.append("</table>")
        
        html_parts.append("""
            <h2>Person Log (Violators Only)</h2>
            <table>
                <tr>
                    <th>Track ID</th>
                    <th>Violations</th>
                    <th>Details</th>
                </tr>
        """)
        for tid, profile in profiles.items():
            if profile.violation_count > 0:
                details = ", ".join([f"{k} ({v})" for k, v in profile.violation_types.items()])
                html_parts.append(f"""
                    <tr>
                        <td>Person-{tid}</td>
                        <td>{profile.violation_count}</td>
                        <td>{details}</td>
                    </tr>
                """)
        html_parts.append("</table>")
    else:
        html_parts.append("<p><em>No safety violations were detected during this session. Great job!</em></p>")

    html_parts.append("""
            <br>
            <p style="font-size: 12px; color: #6b7280;">This is an automated safety report generated by VioTrack.</p>
        </body>
    </html>
    """)
    
    html_content = "".join(html_parts)
    
    # Generate the LaTeX File representation
    latex_content = generate_latex_report(
        profiles, duration, total_persons, total_violations, 
        compliance_score, compliance_status, violation_counts
    )

    pdf_path = None
    tex_path = None
    temp_dir = tempfile.mkdtemp()
    
    try:
        tex_path = os.path.join(temp_dir, "report.tex")
        with open(tex_path, "w", encoding="utf-8") as f:
            f.write(latex_content)
        
        # Check if pdflatex exists to compile into a beautiful PDF
        if shutil.which("pdflatex"):
            subprocess.run(["pdflatex", "-interaction=nonstopmode", "-output-directory", temp_dir, tex_path], 
                           check=True, capture_output=True)
            candidate_pdf = os.path.join(temp_dir, "report.pdf")
            if os.path.exists(candidate_pdf):
                pdf_path = candidate_pdf
    except Exception as e:
        logger.error(f"Failed to generate latex pdf: {e}")

    # Check if SMTP is configured
    if not settings.SMTP_SERVER or not settings.SMTP_USERNAME or not settings.SMTP_PASSWORD:
        logger.info(f"--- MOCK EMAIL START ---")
        logger.info(f"To: {recipient}")
        logger.info(f"Subject: [VioTrack] Live Stream Batch Report - {total_violations} Violations")
        logger.info("HTML Body generated successfully. Setup SMTP credentials in .env to actually send this over the internet.")
        logger.info(f"LaTeX report generated at {tex_path}. PDF: {pdf_path}")
        logger.info(f"--- MOCK EMAIL END ---")
        # Cleanup temp directory since mock email is used
        try:
            shutil.rmtree(temp_dir)
        except:
            pass
        return

    # Send the email via SMTP
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[VioTrack] Live Stream Batch Report - {total_violations} Violations"
        msg["From"] = settings.SMTP_USERNAME
        msg["To"] = recipient

        # Attach HTML Body
        part = MIMEText(html_content, "html")
        msg.attach(part)
        
        # Attach the LaTeX PDF (if compiled successfully)
        if pdf_path and os.path.exists(pdf_path):
            with open(pdf_path, "rb") as f:
                attach_pdf = MIMEApplication(f.read(), _subtype="pdf")
                attach_pdf.add_header('Content-Disposition', 'attachment', filename='VioTrack_Safety_Report.pdf')
                msg.attach(attach_pdf)
        # Fallback: Attach the raw .tex file
        elif tex_path and os.path.exists(tex_path):
            with open(tex_path, "rb") as f:
                attach_tex = MIMEApplication(f.read(), _subtype="x-tex")
                attach_tex.add_header('Content-Disposition', 'attachment', filename='VioTrack_Safety_Report.tex')
                msg.attach(attach_tex)

        server = smtplib.SMTP(settings.SMTP_SERVER, settings.SMTP_PORT)
        server.starttls()
        server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
        server.sendmail(settings.SMTP_USERNAME, recipient, msg.as_string())
        server.quit()
        logger.info(f"Batch report email successfully sent to {recipient}")
    except Exception as e:
        logger.error(f"Failed to send email to {recipient}: {e}")
    finally:
        # Final cleanup for temp directory
        try:
            shutil.rmtree(temp_dir)
        except:
            pass

